import React from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import { J } from "@/components/Icons";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import wavelength from "../../public/images/projects/Wavelength_Cover.png";
import slack from "../../public/images/projects/slack_clone_cover.png";
import crim_search from "../../public/images/projects/crim_search_cover.png";
import meetup from "../../public/images/projects/meetup_cover.png";
import quoted from "../../public/images/projects/Quoted_Cover.png";
import aiToolsForContentCreators from "../../public/images/projects/ai_tools_for_content_creators.png";
import { GithubIcon } from "@/components/Icons";
import { Download } from "lucide-react";
import { Project } from "@/pages/projects";
import {
  ArrowBigRightDash,
  CornerDownRight,
  MoveDownRight,
  TrendingDown,
  ArrowDownCircle,
} from "lucide-react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Johnny Avila</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full mb-16 flex flex-col items-center justify-center">
        <Layout className="pt-[4rem] ">
          <AnimatedText
            className="mb-[4rem] lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!test-4xl"
            text={"Coding is the art of ideas brought to life."}
          />
          <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
            <div className="col-span-12">
              <div className="flex flex-row items-center justify-around mb-10 md:flex-col md:justify-items-center">
                {/* <h1 class="w-2/5 bg-gradient-to-tr from-sky-950 to-sky-600 bg-clip-text font-sans text-3xl font-bold leading-tight tracking-normal text-transparent antialiased text-right md:w-full md:text-center">
                  {`Currently learning Next.js 14, Prisma, and NextAuth by working on`}
                </h1> */}
                <h1 class="w-2/5 text-4xl font-extrabold leading-none tracking-tight text-right md:w-full md:text-center md:mt-20 md:mb-8">
                  Currently learning{" "}
                  <span class="text-fuchsia-700">Next.js 14,</span>{" "}
                  <span class="text-fuchsia-800">Prisma,</span> <span>and</span>{" "}
                  <span class="text-fuchsia-900 dark:text-blue-500">
                    NextAuth
                  </span>{" "}
                  by working on
                </h1>
                <TrendingDown size={100} className="md:mb-[3rem]" />
                <Project
                  title={"AI Tool Aggregator"}
                  summary={`Aggregator site for AI-Powered Tools for Content Creators`}
                  link={`https://aitoolaggregator-johnny-2123.vercel.app/`}
                  github={`https://github.com/johnny-2123/AI-Tool-Aggregator-Site`}
                  type={`(In Progress) `}
                  img={aiToolsForContentCreators}
                />
              </div>
              <h1 class="mb-16 mt-20 md:mt-16 text-6xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl sm:text-4xl text-center dark:text-white">
                <span class="underline underline-offset-3 decoration-8 decoration-primary">
                  Projects
                </span>{" "}
              </h1>
              <ArrowDownCircle size={100} className="mx-auto mb-16" />
              <FeaturedProject
                title={"Wavelength"}
                summary={`Wavelength is real-time multiplayer word association game. Built with Node.js, PostgreSQL, React, Redux, and WebSockets, Wavelength allows users to create, join, and manage games and friend relationships. It offers real-time gameplay, game history, friend requests, and various interactive features.`}
                link={`https://wavelength-2hp9.onrender.com/`}
                github={`https://github.com/johnny-2123/Wavelength`}
                type={`Feautured Project`}
                img={wavelength}
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                title={"Quoted"}
                summary={`Quoted is a web application that allows users to share and discover quotes. Powered by Next.js, Tailwind CSS and Firebase, users can create, edit, delete, quotes. Users can also like quotes and follow their favorite quote creators.`}
                link={`https://quoted-phi.vercel.app/`}
                github={`https://github.com/johnny-2123/Quoted`}
                type={`Feautured Project`}
                img={quoted}
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                title={"Meetup Clone"}
                summary={`Meetup Clone is a web application that allows users to join groups and attend events based on shared interests. Developed using JavaScript, React, Redux, Sequelize, HTML5, CSS3, Node.js, Express.js, and Render. `}
                link={`https://meetupclone-ndtq.onrender.com/`}
                github={`https://github.com/johnny-2123/Meetup_Clone`}
                type={`Feautured Project`}
                img={meetup}
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                title={"Crim Search"}
                summary={`A paralegal-focused Chrome Extension that optimizes criminal history chart creation, reducing time by 50%. Extracts criminal case data for MD, DC, and VA, utilizing Chrome local storage and messaging system for efficient data management.`}
                link={`https://chrome.google.com/webstore/detail/crim-search/jofkolbgfgfpjdfcjhjefefbnidoamcd?hl=en&authuser=2`}
                github={`https://github.com/johnny-2123/Crim-Search-Extension`}
                // type={`Feautured Project`}
                img={crim_search}
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                title={"Slack Clone"}
                summary={`This is a clone of the popular communication platform Slack. It provides a comprehensive set of features to facilitate seamless communication and collaboration within workspaces.The project's backend is built on Flask and SQLAlchemy. The project's frontend is built on React and Redux. Realtime chat message functionality is handled with SocketIO.`}
                link={`https://aaslackcloneproject.onrender.com/`}
                github={`https://github.com/johnny-2123/Slack_Clone`}
                // type={`Feautured Project`}
                img={slack}
              />
            </div>
          </div>
        </Layout>
      </main>
      <main className="flex items-center text-dark w-full min-h-screen ">
        <Layout className="!pt-0 mt-0 md:pt-0 sm:pt-0 flex content-start ">
          <div
            className={`flex items-center justify-between w-full mt-[0rem] lg:flex-col`}
          >
            <div className={`w-2/5`}>
              <J className={`w-3/4 h-auto lg:hidden md:inline-block  `} />
            </div>
            <div
              className={`w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center`}
            >
              <AnimatedText
                text={`Coding Ideas Into Digital Realities.`}
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl xs:!text-2xl"
              />
              <br />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a versatile full-stack developer, I thrive on breathing life
                into ideas through the medium of web applications. Browse my
                selection of projects that showcase my proficiency in React.js
                and the wider field of web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Avila_Johnny_Resume_.pdf "
                  target={"_blank"}
                  className={`flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark border-2`}
                  download={true}
                >
                  Resume <Download className="ml-2" />
                </Link>
                <Link
                  href="mailto:avila.johnny11@gmail.com"
                  className={`ml-4 text-lg font-medium capitalize text-dark underline `}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        <div className="absolute right-8 bottom-6 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt="light bulb"
            className="w-[70%] h-auto"
            priority={true}
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
          />
        </div>
      </main>
    </>
  );
}

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
  return (
    <article className="w-full flex items-center justify-between rounded-3xl rounded-br-2xl border border-solid border-dark bg-light shadow-2xl p-12 relative  lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4 ">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl xs:-right-2 sm:h-[102%] xs:w-[100%] xs:rounded-[1.5rem]"></div>
      <Link
        href={link}
        target={"_blank"}
        className="w-3/5 cursor-pointer overflow-hidden rounded-xl lg:w-full"
      >
        <Image
          src={img}
          alt={title}
          className="w-full h-auto"
          priority={true}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
      </Link>
      <div className="w-2/5 flex flex-col items-start justify-between pl-6 lg:w-full lg:pl-0 lg:pt-6">
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link
          href={link}
          target={"_blank"}
          className="hover:underline underline-offset-[.2rem]"
        >
          <h2 className="my-2 w-full text-left text-4xl font-bold sm:text-md">
            {title}
          </h2>
        </Link>
        <p className="my-2 sm:text-sm">{summary}</p>
        <div className="mt-2 flex items-center">
          <Link href={github} target={"_blank"} className="w-10">
            <GithubIcon />
          </Link>
          <Link
            href={link}
            target={"_blank"}
            className="ml-4 rounded-lg bg-dark text-light p-2 px-6 text-large font-semibold sm:px-4 sm:text-base"
          >
            Live Site
          </Link>
        </div>
      </div>
    </article>
  );
};
