import React, { useRef } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import { J } from "@/components/Icons";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import fatDownArrow from "../../public/images/svgs/fat-down-arrow.svg";
import wavelength from "../../public/images/projects/Wavelength_Cover.png";
import slack from "../../public/images/projects/slack_clone_cover.png";
import crim_search from "../../public/images/projects/crim_search_cover.png";
import meetup from "../../public/images/projects/meetup_cover.png";
import quoted from "../../public/images/projects/Quoted_Cover.png";
import interviewIgnitor from "../../public/images/projects/interview_ignitor.png";
import { GithubIcon } from "@/components/Icons";
import { Download } from "lucide-react";
import { Project } from "@/pages/projects";
import CurrentRole from "@/components/CurrentRole";
import {
  ArrowBigRightDash,
  CornerDownRight,
  MoveDownRight,
  TrendingDown,
  ArrowDownCircle,
} from "lucide-react";
import { ExperienceItem } from "@/components/Experience";
export default function Home() {
  const projectsRef = useRef(null);

  return (
    <>
      <Head>
        <title>Johnny Avila</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full min-h-screen mx-auto max-w-7xl text-dark">
        <Layout className="!pt-0 mt-0 md:pt-0 sm:pt-0 flex content-start ">
          <div
            className={`flex items-center justify-between w-full mt-[0rem] lg:flex-col`}
          >
            <div className={`w-2/5`}>
              <J className={`w-3/4 h-auto lg:hidden md:inline-block  `} />
            </div>
            <div
              className={`w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center`}
            >
              <AnimatedText
                text={`Coding Ideas Into Digital Realities.`}
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl xs:!text-2xl"
              />
              <br />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a versatile full-stack developer, I thrive on breathing life
                into ideas through the medium of web applications. Browse my
                selection of projects that showcase my proficiency in React.js
                and the wider field of web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Avila_Johnny_Resume_.pdf "
                  target={"_blank"}
                  className={`flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-solid border-transparent hover:border-dark border-2`}
                  download={true}
                >
                  Resume <Download className="ml-2" />
                </Link>
                <Link
                  href="mailto:avila.johnny11@gmail.com"
                  className={`ml-4 text-lg font-medium capitalize text-dark underline `}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute inline-block w-24 right-8 bottom-6 md:hidden hover:cursor-pointer">
          <Image
            src={fatDownArrow}
            onClick={() => {
              if (projectsRef.current) {
                projectsRef.current.scrollIntoView({
                  behavior: "smooth",
                  block: "start",
                });
              }
            }}
            alt="light bulb"
            className="w-[70%] h-auto"
            priority={true}
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
          />
        </div>
      </main>
      <main
        ref={projectsRef}
        className="flex flex-col items-center justify-center w-full mx-auto mb-16 max-w-7xl"
      >
        <Layout className="pt-[2rem] ">
          {/* <AnimatedText
            className="mb-[4rem] lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!test-4xl"
            text={"Coding is the art of ideas brought to life."}
          /> */}
          <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
            <div className="col-span-12">
              <div className="flex flex-row items-center justify-around mb-10 md:flex-col md:justify-items-center">
                <h1 className="w-2/5 text-4xl font-extrabold leading-none tracking-tight text-right md:w-full md:text-center md:mt-20 md:mb-8">
                  Developing with{" "}
                  <span className="text-fuchsia-700">Next.js 14,</span>{" "}
                  <span className="text-fuchsia-800">Prisma,</span>{" "}
                  <span>and</span>{" "}
                  <span className="text-fuchsia-900 dark:text-blue-500">
                    React 18
                  </span>{" "}
                  by working on
                </h1>
                <TrendingDown size={100} className="md:mb-[3rem]" />
                <Project
                  title={"Interview Igniter"}
                  summary={`Collection of AI-based practice tools designed to help job seekers excel in interviews.`}
                  link={`https://www.interviewigniter.com/`}
                  github={`https://github.com/johnny-2123`}
                  type={`Contract Work`}
                  img={interviewIgnitor}
                />
              </div>
              <div className="flex items-center justify-center col-span-12 mt-32 mb-24 md:flex-col">
                <h1 className="mx-auto mb-2 text-6xl font-extrabold leading-none tracking-tight text-center text-gray-900 w-fit md:mt-16 md:text-5xl sm:text-4xl dark:text-white">
                  <span className="underline underline-offset-3 decoration-8 decoration-primary">
                    Current Role
                  </span>
                </h1>
                <CurrentRole />
              </div>
              <h1 className="mt-20 mb-5 text-6xl font-extrabold leading-none tracking-tight text-center text-gray-900 md:mt-16 md:text-5xl sm:text-4xl dark:text-white">
                <span className="underline underline-offset-3 decoration-8 decoration-primary">
                  Projects
                </span>{" "}
              </h1>
              <ArrowDownCircle size={100} className="mx-auto mb-5" />
              <FeaturedProject
                title={"Wavelength"}
                summary={`Wavelength is real-time multiplayer word association game. Built with Node.js, PostgreSQL, React, Redux, and WebSockets, Wavelength allows users to create, join, and manage games and friend relationships. It offers real-time gameplay, game history, friend requests, and various interactive features.`}
                link={`https://wavelength-2hp9.onrender.com/`}
                github={`https://github.com/johnny-2123/Wavelength`}
                type={`Feautured Project`}
                img={wavelength}
              />
            </div>
            {projects.map((project) => (
              <div className="col-span-12" key={project.title}>
                <FeaturedProject
                  title={project.title}
                  summary={project.summary}
                  link={project.link}
                  github={project.github}
                  type={project.type || "Feautured Project"}
                  img={project.img}
                />
              </div>
            ))}
          </div>
        </Layout>
      </main>
    </>
  );
}

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
  return (
    <article className="relative flex items-center justify-between w-full p-12 border border-solid shadow-2xl rounded-3xl rounded-br-2xl border-dark bg-light lg:flex-col lg:p-8 xs:rounded-2xl xs:rounded-br-3xl xs:p-4 ">
      <div className="absolute top-0 -right-3 -z-10 w-[101%] h-[103%] rounded-[2.5rem] bg-dark rounded-br-3xl xs:-right-2 sm:h-[102%] xs:w-[100%] xs:rounded-[1.5rem]"></div>
      <Link
        href={link}
        target={"_blank"}
        className="w-3/5 overflow-hidden cursor-pointer rounded-xl lg:w-full"
      >
        <Image
          src={img}
          alt={title}
          className="w-full h-auto"
          priority={true}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
      </Link>
      <div className="flex flex-col items-start justify-between w-2/5 pl-6 lg:w-full lg:pl-0 lg:pt-6">
        <span className="text-xl font-medium text-primary">{type}</span>
        <Link
          href={link}
          target={"_blank"}
          className="hover:underline underline-offset-[.2rem]"
        >
          <h2 className="w-full my-2 text-4xl font-bold text-left sm:text-md">
            {title}
          </h2>
        </Link>
        <p className="my-2 sm:text-sm">{summary}</p>
        <div className="flex items-center mt-2">
          <Link href={github} target={"_blank"} className="w-10">
            <GithubIcon />
          </Link>
          <Link
            href={link}
            target={"_blank"}
            className="p-2 px-6 ml-4 font-semibold rounded-lg bg-dark text-light text-large sm:px-4 sm:text-base"
          >
            Live Site
          </Link>
        </div>
      </div>
    </article>
  );
};

const projects = [
  {
    title: "Quoted",
    summary:
      "Quoted is a web application that allows users to share and discover quotes. Powered by Next.js, Tailwind CSS and Firebase, users can create, edit, delete, quotes. Users can also like quotes and follow their favorite quote creators.",
    link: "https://quoted-phi.vercel.app/",
    github: "https://github.com/johnny-2123/Quoted",
    type: "Feautured Project",
    img: quoted,
  },
  {
    title: "Meetup Clone",
    summary:
      "Meetup Clone is a web application that allows users to join groups and attend events based on shared interests. Developed using JavaScript, React, Redux, Sequelize, HTML5, CSS3, Node.js, Express.js, and Render.",
    link: "https://meetupclone-ndtq.onrender.com/",
    github: "https://github.com/johnny-2123/Meetup_Clone",
    type: "Feautured Project",
    img: meetup,
  },
  {
    title: "Crim Search",
    summary:
      "A paralegal-focused Chrome Extension that optimizes criminal history chart creation, reducing time by 50%. Extracts criminal case data for MD, DC, and VA, utilizing Chrome local storage and messaging system for efficient data management.",
    link: "https://chrome.google.com/webstore/detail/crim-search/jofkolbgfgfpjdfcjhjefefbnidoamcd?hl=en&authuser=2",
    github: "https://github.com/johnny-2123/Crim-Search-Extension",
    img: crim_search,
  },
  {
    title: "Slack Clone",
    summary:
      "This is a clone of the popular communication platform Slack. It provides a comprehensive set of features to facilitate seamless communication and collaboration within workspaces.The project's backend is built on Flask and SQLAlchemy. The project's frontend is built on React and Redux. Realtime chat message functionality is handled with SocketIO.",
    link: "https://aaslackcloneproject.onrender.com/",
    github: "https://github.com/johnny-2123/Slack_Clone",
    img: slack,
  },
];
